name: 04-using-action

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Using the checkout action'
        uses: action/checkout@v4
      
      - name: 'Printing folders'
        run: ls
