name: 04 - Using Actions

on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '23.5.0'
            
            - name: Install Dependencies
              run: npm ci
              working-directory: ./04-using-actions/react-app


           