name: 05 - 2 - Event Filters and Activity Types

on: 
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: "Testing Event Filters and Activity Types 02"
        run: echo "Running whenever a PR is closed."