name: 07 - Using Expressions

on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                description: 'Debug mode'
                required: false
                default: 'false'

jobs:
    echo:
        runs-on: ubuntu-latest

        steps:
            - name: Print start-up data
              if: inputs.debug == 'true'
              run: | 
                echo "Triggered by: ${{ github.event_name }}"
                echo "Branch: ${{ github.ref }}"
                echo "SHA: ${{ github.sha }}"
                echo "OS: ${{ runner.os }}"
        
            - name: Print when triggered from main
              if: ${{ github.ref == 'refs/heads/main' && inputs.debug == 'true' }}
              run: echo "I was triggered from main"

            - name: Greetings
              run: echo "Hello, ${{ github.actor }}!"
            
